services:
  frontend:
    container_name: kisscsemege-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./dist:/usr/share/caddy
    environment:
      - NODE_ENV=production
    networks:
      - caddy_net
      - monitoring

  server:
    container_name: kisscsemege-server
    build:
      context: ./server
      dockerfile: Dockerfile.server
    environment:
      - NODE_ENV=production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - PORT=5100
    env_file:
      - .env
    networks:
      - caddy_net
      - monitoring

networks:
  caddy_net:
    external: true
  monitoring:
    external: true
