name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS to known hosts
        run: ssh-keyscan -H 75.119.139.125 >> ~/.ssh/known_hosts

      - name: Copy files via SCP
        run: scp -r ./* deployuser@75.119.139.125:/home/deployuser/docker/apps/kisscsemege

      - name: SSH and deploy
        run: |
          ssh deployuser@75.119.139.125 << 'EOF'
            cd /home/deployuser/docker/apps/kisscsemege
            docker compose down
            docker compose -f docker-compose.prod.yml up -d --build
          EOF
